In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df=pd.read_csv(r"C:\Users\admin\OneDrive\Documents\crime_incidents.csv")
pd.set_option('display.max_columns', None)

In [4]:
df

,incident_id,crime_type,district,city,state,address,latitude,longitude,incident_datetime,officer_id,officer_first_name,officer_last_name,badge_number,suspect_id,suspect_first_name,suspect_last_name,suspect_age,suspect_gender,suspect_race,victim_id,victim_first_name,victim_last_name,victim_age,victim_gender,victim_phone,weapon_used,severity,case_status,resolution,num_arrests,property_loss_usd,reported_online,notes
0,INC001115,asslt,Sou,Maplewood,GA,2830 Cedar Lane,170.284100,-77.500710,2024-04-16 08:45:03,OFF0078,Emily,Davis,1342.0,SUS00281,Barbara,Thomas,51.0,MALE,asian,VIC00642,Robert,Torres,51.0,Unknown,6223265920,Firearm,2,Open,No Arrest,NaN,NaN,True,Incident at 2830 Cedar Lane. Officer responded...
1,INC004706,burglary,southeast,Maplewood,OH,2361 Park Rd,29.422717,-77.167016,2022-01-11 22:03:29,OFF0059,Michelle,Green,5133.0,SUS00376,Barbara,Harris,-28.0,Other,Black,VIC00262,John,Martin,231.0,NaN,241-973-4826,Firearm,3,NaN,NaN,2.0,44839.49,yes,Incident at 2361 Park Rd. Officer responded at...
2,INC002249,Homocide,Southwest,Lakewood,AZ,1067 Main St,39.411460,-98.615298,2022-04-14 11:39:24,OFF0088,Michael,White,7781.0,SUS00560,Richard,Scott,19.0,F,asian,VIC00518,Richard,Hill,29.0,Other,244-584-7696,KNIFE,1,CLOSED,warning,2.0,15963.38,YES,Incident at 1067 Main St. Officer responded at...
3,INC000021,Property Damage,Cen,Springfield,AZ,4713 Washington Ave,28.633439,-99.030051,2020-12-09 15:14:24,OFF0077,Chris,Jackson,5097.0,SUS00468,Michael,Thomas,262.0,MALE,Black,VIC00243,Susan,Young,243.0,NaN,5021227484,hands,Low,Resolved,NaN,5.0,48680.14,False,Incident at 4713 Washington Ave. Officer respo...
4,INC000488,Domestc Violence,North,Lakewood,PA,1371 River Rd,34.217850,-121.614731,2021-07-24 20:08:13,OFF0083,Susan,Flores,6220.0,SUS00751,Thomas,Jackson,75.0,female,white,VIC00512,Thomas,Thomas,51.0,M,9698766873,Unarmed,MEDIUM,Closed,Warning Issued,2.0,23513.01,YES,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5245,INC003247,Burglary,Nor,Springfield,OH,4434 Elm Blvd,42.576022,-79.788519,2021-12-18 17:27:18,OFF0005,Matthew,Wilson,6976.0,SUS00631,Susan,Brown,60.0,F,White,VIC00053,Ashley,Taylor,84.0,m,534-870-3834,NaN,Medium,NaN,Arrest Made,2.0,44417.98,NaN,NaN
5246,INC000314,Vandlism,NORTHWEST,Maplewood,FL,1065 Sunset Blvd,38.941858,-108.480924,2023-06-23 04:09:19,OFF0132,Patricia,Harris,4666.0,SUS00706,Richard,Hill,36.0,NaN,Hispanic,VIC00712,Joseph,Anderson,-75.0,female,NaN,NaN,2,Pending,NaN,5.0,16330.48,no,Incident at 1065 Sunset Blvd. Officer responde...
5247,INC002761,Arson,northwest,Fairview,FL,6419 Sunset Blvd,41.627732,-82.048681,2018-04-25 14:38:24,OFF0003,Robert,Smith,8076.0,NaN,NaN,NaN,NaN,NaN,NaN,VIC00018,David,Thompson,77.0,Other,796-911-1169,blunt object,4,CLOSED,NaN,4.0,13138.25,NaN,Incident at 6419 Sunset Blvd. Officer responde...
5248,INC001022,Scam,East,Maplewood,TX,9087 River Rd,28.903176,-111.840384,2023-03-29 09:54:50,OFF0028,Chris,Thomas,8271.0,SUS00566,Chris,White,35.0,NaN,NaN,VIC00959,Daniel,Wilson,72.0,female,214-897-2917,NaN,NaN,closed,arrest made,1.0,43851.12,0,Incident at 9087 River Rd. Officer responded a...
5249,INC003216,VANDALISM,west,Springfield,NY,3781 Sunset Blvd,30.859979,-78.590392,09-08-2022,OFF0102,Jessica,Harris,9531.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CRITICAL,OPEN,arrest made,2.0,38856.84,No,Incident at 3781 Sunset Blvd. Officer responde...

In [5]:
print("Shape:",df.shape)
print("\nColumns and Info:")
print(df.info())
print("\nFirst 5 rows:")
print(df.head())

Shape: (5250, 33)

Columns and Info:
<class 'pandas.DataFrame'>
RangeIndex: 5250 entries, 0 to 5249
Data columns (total 33 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   incident_id         5250 non-null   str
 1   crime_type          5250 non-null   str
 2   district            5250 non-null   str
 3   city                5250 non-null   str
 4   state               5250 non-null   str
 5   address             5250 non-null   str
 6   latitude            4992 non-null   float64
 7   longitude           4961 non-null   float64
 8   incident_datetime   4910 non-null   str
 9   officer_id          5250 non-null   str
 10  officer_first_name  5250 non-null   str
 11  officer_last_name   5250 non-null   str
 12  badge_number        4938 non-null   float64
 13  suspect_id          4440 non-null   str
 14  suspect_first_name  4440 non-null   str
 15  suspect_last_name   4440 non-null   str
 16  suspect_age         4153 non-null   float64
 17  suspect_gender      3837 non-null   str
 18  suspect_race        3649 non-null   str
 19  victim_id           4993 non-null   str
 20  victim_first_name   4993 non-null   str
 21  victim_last_name    4993 non-null   str
 22  victim_age          4688 non-null   float64
 23  victim_gender       4250 non-null   str
 24  victim_phone        4194 non-null   str
 25  weapon_used         4280 non-null   str
 26  severity            4895 non-null   str
 27  case_status         4519 non-null   str
 28  resolution          4299 non-null   str
 29  num_arrests         4917 non-null   float64
 30  property_loss_usd   4814 non-null   str
 31  reported_online     4746 non-null   str
 32  notes               4181 non-null   str
dtypes: float64(6), str(27)
memory usage: 1.3 MB
None

First 5 rows:
  incident_id        crime_type     district         city state  \
0   INC001115             asslt          Sou    Maplewood    GA
1   INC004706          burglary    southeast    Maplewood    OH
2   INC002249          Homocide  Southwest       Lakewood    AZ
3   INC000021   Property Damage          Cen  Springfield    AZ
4   INC000488  Domestc Violence        North     Lakewood    PA

               address    latitude   longitude    incident_datetime  \
0      2830 Cedar Lane  170.284100  -77.500710  2024-04-16 08:45:03
1         2361 Park Rd   29.422717  -77.167016  2022-01-11 22:03:29
2         1067 Main St   39.411460  -98.615298  2022-04-14 11:39:24
3  4713 Washington Ave   28.633439  -99.030051  2020-12-09 15:14:24
4        1371 River Rd   34.217850 -121.614731  2021-07-24 20:08:13

  officer_id officer_first_name officer_last_name  badge_number suspect_id  \
0    OFF0078              Emily             Davis        1342.0   SUS00281
1    OFF0059           Michelle             Green        5133.0   SUS00376
2    OFF0088            Michael             White        7781.0   SUS00560
3    OFF0077              Chris           Jackson        5097.0   SUS00468
4    OFF0083              Susan            Flores        6220.0   SUS00751

  suspect_first_name suspect_last_name  suspect_age suspect_gender  \
0            Barbara            Thomas         51.0           MALE
1            Barbara            Harris        -28.0          Other
2            Richard             Scott         19.0              F
3            Michael            Thomas        262.0           MALE
4             Thomas           Jackson         75.0         female

  suspect_race victim_id victim_first_name victim_last_name  victim_age  \
0        asian  VIC00642            Robert           Torres        51.0
1        Black  VIC00262              John           Martin       231.0
2        asian  VIC00518           Richard             Hill        29.0
3        Black  VIC00243             Susan            Young       243.0
4        white  VIC00512            Thomas           Thomas        51.0

  victim_gender  victim_phone weapon_used severity case_status  \
0       Unknown    6223265920     Firearm        2        Open
1           NaN  241-973-4826     Firearm        3         NaN
2         Other  244-584-7696       KNIFE        1      CLOSED
3           NaN    5021227484       hands      Low    Resolved
4             M    9698766873     Unarmed   MEDIUM      Closed

       resolution  num_arrests property_loss_usd reported_online  \
0       No Arrest          NaN               NaN            True
1             NaN          2.0          44839.49             yes
2         warning          2.0          15963.38             YES
3             NaN          5.0          48680.14           False
4  Warning Issued          2.0          23513.01             YES

                                               notes
0  Incident at 2830 Cedar Lane. Officer responded...
1  Incident at 2361 Park Rd. Officer responded at...
2  Incident at 1067 Main St. Officer responded at...
3  Incident at 4713 Washington Ave. Officer respo...
4                                                NaN

In [57]:
print("duplicates:", df.duplicated().sum(), df['incident_id'].duplicated().sum())

duplicates: 200 200

In [104]:
crime_clean_df=df.copy()

In [105]:
initial_rows=len(crime_clean_df)
crime_clean_df = crime_clean_df.drop_duplicates(subset=['incident_id'], keep='first')
duplicate_rows = len(crime_clean_df)

In [145]:
duplicate_rows

5050

In [108]:
# inspecting categorical unique values, anomalies, types and column by column and cleaning , standardization data

In [109]:
print("crime_type unique:", df['crime_type'].unique())

crime_type unique: <StringArray>
[              'asslt',            'burglary',            'Homocide',
     'Property Damage',    'Domestc Violence', 'Breaking & Entering',
             'robbery',        'manslaughter',                 'B&E',
           'Narcotics',
 ...
           '  FRAUD  ', 'FRAUDULENT ACTIVITY',       'Drug  Offence',
              '  DV  ',                'SCAM',     '  Sex Assault  ',
   'assault & battery',        'CYBER  CRIME',             '  dui  ',
   '  theft/larceny  ']
Length: 182, dtype: str

In [110]:
crime_mapping={
    "asslt":"Assault","assault":"Assault","battery":"Assault","assault & battery":"Assault","homocide":"Homicide",
    "homicide":"Homicide","murder":"Homicide","manslaughter":"Homicide","burglary":"Burglary","burglry":"Burglary",
    "b&e":"Burglary","breaking & entering":"Burglary","robbery":"Robbery","robbry":"Robbery","roberry":"Robbery",
    "armed robbery":"Robbery","theft":"Theft","larceny":"Theft","theft/larceny":"Theft","stealing":"Theft",
    "dv":"Domestic Violence", "dom. violence": "Domestic Violence", "domestc violence":"Domestic Violence",
    "domestic violence": "Domestic Violence","sa":"Sexual Assault", "sex assault": "Sexual Assault", "sexual assault": "Sexual Assault",
    "sexual assualt": "Sexual Assault", "dui":"DUI","duii": "DUI","dwi": "DUI","d.u.i.": "DUI","drunk driving": "DUI",
    "drugs":"Drug Offense","narcotics": "Drug Offense","drug offense": "Drug Offense","drug offence":"Drug Offense",
    "fraud":"Fraud", "fraudulent activity": "Fraud", "online fraud": "Fraud", "scam": "Fraud","deception":"Fraud",
    "arson":"Arson", "arsen":"Arson","fire setting": "Arson", "vandalism": "Vandalism",
    "vandlism":"Vandalism","graffiti":"Vandalism","property damage":"Vandalism","trespass":"Trespassing","trespassing": "Trespassing",
     "tresspassing":"Trespassing", "kidnapping": "Kidnapping","kidnaping":"Kidnapping","abduction":"Kidnapping",
    "cyber crime":"Cybercrime","cybercrime":"Cybercrime","hacking":"Cybercrime",
}

crime_clean_df["crime_type_clean"] = (crime_clean_df["crime_type"]
.astype(str).str.strip().str.lower()
.str.replace(r'\s+', ' ', regex=True)
.map(crime_mapping)
)

In [111]:
crime_clean_df.crime_type_clean.unique()

<StringArray>
[          'Assault',          'Burglary',          'Homicide',
         'Vandalism', 'Domestic Violence',           'Robbery',
      'Drug Offense',             'Theft',             'Fraud',
             'Arson',        'Kidnapping',       'Trespassing',
        'Cybercrime',    'Sexual Assault',               'DUI']
Length: 15, dtype: str

In [112]:
print("district unique:", df['district'].unique())

district unique: <StringArray>
[           'Sou',     ' southeast',    'Southwest  ',            'Cen',
         ' North',         'East  ',      'southeast',        'midtown',
      'northeast',        'CENTRAL',
 ...
  '  Northeast  ',      '   West  ',     '   North  ',            'eas',
  '  northwest  ', '   Southeast  ',     '  West    ',    'southeast  ',
            'mid',  '  northeast  ']
Length: 131, dtype: str

In [113]:
district_map={
    "sou":"South",
    "cen":"Central",
    "nor":"North",
    "eas":"East",
    "mid":"Midtown",
    "wes":"West",
}
crime_clean_df["district_clean"]=(
    crime_clean_df["district"]
    .str.strip()
    .str.lower()
    .replace(district_map)
    .str.title()

)

In [114]:
crime_clean_df.district_clean.unique()

<StringArray>
[    'South', 'Southeast', 'Southwest',   'Central',     'North',      'East',
   'Midtown', 'Northeast',      'West', 'Northwest']
Length: 10, dtype: str

In [115]:
print("state:", df['state'].unique())
print("city:",df['city'].unique())

state: <StringArray>
['GA', 'OH', 'AZ', 'PA', 'CA', 'TX', 'IL', 'NY', 'FL', 'NC']
Length: 10, dtype: str
city: <StringArray>
[  'Maplewood',    'Lakewood', 'Springfield',   'Hillcrest', 'Centerville',
   'Riverside',     'Oakdale',    'Fairview']
Length: 8, dtype: str

In [116]:
print("latitude range:","\nMinimum:",df['latitude'].min(),"\nMaximum:" ,df['latitude'].max())

latitude range:
Minimum: 25.00242
Maximum: 199.9842

In [117]:
print("longitude range:","\nMinimum:",df['longitude'].min(),"\nMaximum:" ,df['longitude'].max())

longitude range:
Minimum: -121.975849
Maximum: 99.7873

In [118]:
crime_clean_df["latitude_clean"] = np.where(crime_clean_df["latitude"].between(24.0,50.0), crime_clean_df["latitude"],np.nan)

In [119]:
crime_clean_df["longitude_clean"] = np.where(crime_clean_df["longitude"].between(-124.77,-66.95),crime_clean_df["longitude"],np.nan)

In [120]:
print("suspect_gender unique:", df['suspect_gender'].unique())
print("victim_gender unique:", df['victim_gender'].unique())

suspect_gender unique: <StringArray>
[   'MALE',   'Other',       'F',  'female',       nan,  'Female',       'm',
  'FEMALE',       'M',    'male',    'Male', 'Unknown',       'f']
Length: 13, dtype: str
victim_gender unique: <StringArray>
['Unknown',       nan,   'Other',       'M',  'female',    'male',  'Female',
       'F',    'MALE',       'm',       'f',    'Male',  'FEMALE']
Length: 13, dtype: str

In [121]:
gender_map= {
    "m":"Male", "male":"Male", "f":"Female", "female":"Female", "other":"Other", "unknown":"Unknown",
}
crime_clean_df["suspect_gender_clean"]=(
    crime_clean_df["suspect_gender"]
    .astype(str).str.strip().str.lower().map(gender_map)
)
crime_clean_df["victim_gender_clean"]=(
    crime_clean_df["victim_gender"].astype(str).str.strip().str.lower().map(gender_map)
)

In [122]:
crime_clean_df.suspect_gender_clean.unique()

<StringArray>
['Male', 'Other', 'Female', nan, 'Unknown']
Length: 5, dtype: str

In [123]:
crime_clean_df.victim_gender_clean.unique()

<StringArray>
['Unknown', nan, 'Other', 'Male', 'Female']
Length: 5, dtype: str

In [124]:
print("severity:", df['severity'].unique())

severity: <StringArray>
[       '2',        '3',        '1',      'Low',   'MEDIUM',     'high',
        nan,     'Crit',     'High',      'low', 'Critical',        '4',
 'CRITICAL',   'Medium',      'Med']
Length: 15, dtype: str

In [125]:
severity_map = {
    "1":"Low","low":"Low","2":"Medium","med":"Medium","medium":"Medium",
    "3":"High","high":"High","4":"Critical","crit":"Critical","critical":"Critical",
}
crime_clean_df["severity_clean"] = (
    crime_clean_df["severity"].astype(str).str.strip().str.lower().map(severity_map)
)

In [126]:
crime_clean_df.severity_clean.unique()

<StringArray>
['Medium', 'High', 'Low', nan, 'Critical']
Length: 5, dtype: str

In [127]:
#
crime_clean_df["incident_datetime_clean"]=pd.to_datetime(crime_clean_df["incident_datetime"], errors="coerce")
crime_clean_df["year"]=crime_clean_df["incident_datetime_clean"].dt.year
crime_clean_df["month"]=crime_clean_df["incident_datetime_clean"].dt.month
crime_clean_df["day_name"]=crime_clean_df["incident_datetime_clean"].dt.day_name()
crime_clean_df["hour"]=crime_clean_df["incident_datetime_clean"].dt.hour

In [128]:
print("suspect_age range:","\nMinimum", df['suspect_age'].min(),"\nMaximum", df['suspect_age'].max())

suspect_age range:
Minimum -75.0
Maximum 298.0

In [129]:
crime_clean_df["suspect_age_clean"] = np.where(crime_clean_df["suspect_age"].between(0, 110),crime_clean_df["suspect_age"], np.nan)

In [130]:
print("victim_age range:","\nMinimum", df['victim_age'].min(),"\nMaximum", df['victim_age'].max())

victim_age range:
Minimum -90.0
Maximum 298.0

In [131]:
crime_clean_df["victim_age_clean"] = np.where(crime_clean_df["victim_age"].between(0, 110),crime_clean_df["victim_age"], np.nan)

In [132]:
print("weapon_used unique:", df['weapon_used'].unique())

weapon_used unique: <StringArray>
[     'Firearm',        'KNIFE',        'hands',      'Unarmed',
 'Blunt Object',            nan,        'Rifle',          'Bat',
        'Knife',       'Pistol',      'firearm',          'Gun',
   'Hands/Feet', 'blunt object']
Length: 14, dtype: str

In [133]:
weapon_map = {"firearm": "Firearm","pistol": "Firearm","rifle": "Firearm","gun":"Firearm","knife": "Knife",
    "blunt object": "Blunt Object","bat": "Blunt Object","hands": "Hands/Personal","hands/feet": "Hands/Personal",
    "unarmed": "None/Unarmed"}
crime_clean_df["weapon_clean"] = (crime_clean_df["weapon_used"].astype(str).str.strip().str.lower().map(weapon_map)
)

In [134]:
crime_clean_df.weapon_clean.unique()

<StringArray>
['Firearm', 'Knife', 'Hands/Personal', 'None/Unarmed', 'Blunt Object', nan]
Length: 6, dtype: str

In [135]:
print("case_status unique:", df['case_status'].unique())

case_status unique: <StringArray>
[               'Open',                   nan,              'CLOSED',
            'Resolved',              'Closed', 'under investigation',
                'open',        'Investgation', 'Under Investigation',
                'OPEN',              'Pendng',             'Pending',
              'closed']
Length: 13, dtype: str

In [136]:
status_map = {
    "open":"Open","closed":"Closed","resolved":"Closed", "pending":"Pending",
    "pendng":"Pending","under investigation":"Under Investigation","investgation":"Under Investigation",
}
crime_clean_df["case_status_clean"] = (crime_clean_df["case_status"].astype(str).str.strip()
   .str.lower().map(status_map))

In [137]:
crime_clean_df.case_status_clean.unique()

<StringArray>
['Open', nan, 'Closed', 'Under Investigation', 'Pending']
Length: 5, dtype: str

In [138]:
print("resolution unique:", df['resolution'].unique())

resolution unique: <StringArray>
[     'No Arrest',              nan,        'warning', 'Warning Issued',
    'arrest made',      'NO ARREST',      'Dismissed',    'Arrest Made',
     'Arres Made', 'Case Dismissed']
Length: 10, dtype: str

In [139]:
resolution_map = {
    "NO ARREST":"No Arrest","warning":"Warning Issued",
    "arrest made":"Arrest Made", "Arres Made":"Arrest Made",
     "Dismissed":"Case Dismissed",
    
}
crime_clean_df["resolution_clean"] = (crime_clean_df["resolution"].astype(str).str.strip()
   .str.lower().map(resolution_map))

In [140]:
print("reported_online unique:", df['reported_online'].unique())

reported_online unique: <StringArray>
['True', 'yes', 'YES', 'False', 'no', nan, 'Yes', 'No', '1', 'NO', '0']
Length: 11, dtype: str

In [141]:
reported_online_map = {
    "true": True,"yes": True,"1": True, "false": False,"no": False,"0": False,
}
crime_clean_df["reported_online_clean"] = (crime_clean_df["reported_online"] 
       .astype(str).str.strip().str.lower().map(reported_online_map))

In [142]:
crime_clean_df.reported_online_clean.unique()

array([True, False, nan], dtype=object)

In [143]:
loss_numeric = pd.to_numeric(crime_clean_df["property_loss_usd"], errors="coerce")
crime_clean_df["property_loss_usd_clean"] = np.where(loss_numeric >= 0, loss_numeric, np.nan)

In [144]:
print("Initial rows:", initial_rows, "Cleaned unique rows:", len(crime_clean_df))

Initial rows: 5250 Cleaned unique rows: 5050

In [147]:
crime_clean_df

,incident_id,crime_type,district,city,state,address,latitude,longitude,incident_datetime,officer_id,officer_first_name,officer_last_name,badge_number,suspect_id,suspect_first_name,suspect_last_name,suspect_age,suspect_gender,suspect_race,victim_id,victim_first_name,victim_last_name,victim_age,victim_gender,victim_phone,weapon_used,severity,case_status,resolution,num_arrests,property_loss_usd,reported_online,notes,crime_type_clean,district_clean,latitude_clean,longitude_clean,suspect_gender_clean,victim_gender_clean,severity_clean,incident_datetime_clean,year,month,day_name,hour,suspect_age_clean,victim_age_clean,weapon_clean,case_status_clean,resolution_clean,reported_online_clean,property_loss_usd_clean
0,INC001115,asslt,Sou,Maplewood,GA,2830 Cedar Lane,170.284100,-77.500710,2024-04-16 08:45:03,OFF0078,Emily,Davis,1342.0,SUS00281,Barbara,Thomas,51.0,MALE,asian,VIC00642,Robert,Torres,51.0,Unknown,6223265920,Firearm,2,Open,No Arrest,NaN,NaN,True,Incident at 2830 Cedar Lane. Officer responded...,Assault,South,NaN,-77.500710,Male,Unknown,Medium,2024-04-16 08:45:03,2024.0,4.0,Tuesday,8.0,51.0,51.0,Firearm,Open,NaN,True,NaN
1,INC004706,burglary,southeast,Maplewood,OH,2361 Park Rd,29.422717,-77.167016,2022-01-11 22:03:29,OFF0059,Michelle,Green,5133.0,SUS00376,Barbara,Harris,-28.0,Other,Black,VIC00262,John,Martin,231.0,NaN,241-973-4826,Firearm,3,NaN,NaN,2.0,44839.49,yes,Incident at 2361 Park Rd. Officer responded at...,Burglary,Southeast,29.422717,-77.167016,Other,NaN,High,2022-01-11 22:03:29,2022.0,1.0,Tuesday,22.0,NaN,NaN,Firearm,NaN,NaN,True,44839.49
2,INC002249,Homocide,Southwest,Lakewood,AZ,1067 Main St,39.411460,-98.615298,2022-04-14 11:39:24,OFF0088,Michael,White,7781.0,SUS00560,Richard,Scott,19.0,F,asian,VIC00518,Richard,Hill,29.0,Other,244-584-7696,KNIFE,1,CLOSED,warning,2.0,15963.38,YES,Incident at 1067 Main St. Officer responded at...,Homicide,Southwest,39.411460,-98.615298,Female,Other,Low,2022-04-14 11:39:24,2022.0,4.0,Thursday,11.0,19.0,29.0,Knife,Closed,Warning Issued,True,15963.38
3,INC000021,Property Damage,Cen,Springfield,AZ,4713 Washington Ave,28.633439,-99.030051,2020-12-09 15:14:24,OFF0077,Chris,Jackson,5097.0,SUS00468,Michael,Thomas,262.0,MALE,Black,VIC00243,Susan,Young,243.0,NaN,5021227484,hands,Low,Resolved,NaN,5.0,48680.14,False,Incident at 4713 Washington Ave. Officer respo...,Vandalism,Central,28.633439,-99.030051,Male,NaN,Low,2020-12-09 15:14:24,2020.0,12.0,Wednesday,15.0,NaN,NaN,Hands/Personal,Closed,NaN,False,48680.14
4,INC000488,Domestc Violence,North,Lakewood,PA,1371 River Rd,34.217850,-121.614731,2021-07-24 20:08:13,OFF0083,Susan,Flores,6220.0,SUS00751,Thomas,Jackson,75.0,female,white,VIC00512,Thomas,Thomas,51.0,M,9698766873,Unarmed,MEDIUM,Closed,Warning Issued,2.0,23513.01,YES,NaN,Domestic Violence,North,34.217850,-121.614731,Female,Male,Medium,2021-07-24 20:08:13,2021.0,7.0,Saturday,20.0,75.0,51.0,None/Unarmed,Closed,NaN,True,23513.01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5245,INC003247,Burglary,Nor,Springfield,OH,4434 Elm Blvd,42.576022,-79.788519,2021-12-18 17:27:18,OFF0005,Matthew,Wilson,6976.0,SUS00631,Susan,Brown,60.0,F,White,VIC00053,Ashley,Taylor,84.0,m,534-870-3834,NaN,Medium,NaN,Arrest Made,2.0,44417.98,NaN,NaN,Burglary,North,42.576022,-79.788519,Female,Male,Medium,2021-12-18 17:27:18,2021.0,12.0,Saturday,17.0,60.0,84.0,NaN,NaN,Arrest Made,NaN,44417.98
5246,INC000314,Vandlism,NORTHWEST,Maplewood,FL,1065 Sunset Blvd,38.941858,-108.480924,2023-06-23 04:09:19,OFF0132,Patricia,Harris,4666.0,SUS00706,Richard,Hill,36.0,NaN,Hispanic,VIC00712,Joseph,Anderson,-75.0,female,NaN,NaN,2,Pending,NaN,5.0,16330.48,no,Incident at 1065 Sunset Blvd. Officer responde...,Vandalism,Northwest,38.941858,-108.480924,NaN,Female,Medium,2023-06-23 04:09:19,2023.0,6.0,Friday,4.0,36.0,NaN,NaN,Pending,NaN,False,16330.48
5247,INC002761,Arson,northwest,Fairview,FL,6419 Sunset Blvd,41.627732,-82.048681,2018-04-25 14:38:24,OFF0003,Robert,Smith,8076.0,NaN,NaN,NaN,NaN,NaN,NaN,VIC00018,David,Thompson,77.0,Other,796-911-1169,blunt object,4,CLOSED,NaN,4.0,13138.25,NaN,Incident at 6419 Sunset Blvd. Officer responde...,Arson,Northwest,41.627732,-82.048681,NaN,Other,Critical,2018-04-25 14:38:24,2018.0,4.0,Wednesday,14.0,NaN,77.0,Blunt Object,Closed,NaN,NaN,13138.25
5248,INC001022,Scam,East,Maplewood,TX,9087 River Rd,28.903176,-111.840384,2023-03-29 09:54:50,OFF0028,Chris,Thomas,8271.0,SUS00566,Chris,White,35.0,NaN,NaN,VIC00959,Daniel,Wilson,72.0,female,214-897-2917,NaN,NaN,closed,arrest made,1.0,43851.12,0,Incident at 9087 River Rd. Officer responded a...,Fraud,East,28.903176,-111.840384,NaN,Female,NaN,2023-03-29 09:54:50,2023.0,3.0,Wednesday,9.0,35.0,72.0,NaN,Closed,Arrest Made,False,43851.12
5249,INC003216,VANDALISM,west,Springfield,NY,3781 Sunset Blvd,30.859979,-78.590392,09-08-2022,OFF0102,Jessica,Harris,9531.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CRITICAL,OPEN,arrest made,2.0,38856.84,No,Incident at 3781 Sunset Blvd. Officer responde...,Vandalism,West,30.859979,-78.590392,NaN,NaN,Critical,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,Arrest Made,False,38856.84

In [ ]:
#Exploratory Data Analysis

In [ ]:
#1.Overview
num_cols = [
    'suspect_age_clean',
    'victim_age_clean',
    'num_arrests',
    'property_loss_usd_clean',
]
print("NUMERIC SUMMARY")
print(crime_clean_df[num_cols].describe().round(2))

# 2. Categorical Distributions
cat_cols = [
    'crime_type_clean',
    'district_clean',
    'case_status_clean',
    'severity_clean',
    'weapon_clean',
]

for col in cat_cols:
    title = col.replace('_clean', '').replace('_', ' ').upper()
    print(f"\n {title} DISTRIBUTION")
    print(crime_clean_df[col].value_counts().head(10))

#3.online reporting rate
print("\nONLINE REPORTING RATE")
print((crime_clean_df['reported_online_clean'].value_counts(normalize=True) * 100).round(2))


# 4. Incident by year
print("\nINCIDENTS BY YEAR")
print(crime_clean_df['year'].value_counts().sort_index())

NUMERIC SUMMARY
       suspect_age_clean  victim_age_clean  num_arrests  \
count            3675.00           4119.00      4726.00
mean               45.43             49.88         2.26
std                17.45             23.31         1.99
min                15.00             10.00        -5.00
25%                31.00             30.00         1.00
50%                46.00             50.00         2.00
75%                60.00             70.00         4.00
max                75.00             90.00         5.00

       property_loss_usd_clean
count                  4305.00
mean                  24923.12
std                   14422.31
min                      20.66
25%                   12634.61
50%                   24725.40
75%                   37388.31
max                   49998.30

 CRIME TYPE DISTRIBUTION
crime_type_clean
Fraud             437
DUI               353
Arson             352
Drug Offense      350
Homicide          339
Theft             339
Kidnapping        332
Sexual Assault    326
Robbery           324
Trespassing       323
Name: count, dtype: int64

 DISTRICT DISTRIBUTION
district_clean
North        696
South        668
Central      520
West         517
Midtown      513
East         458
Southwest    444
Northeast    436
Northwest    407
Southeast    391
Name: count, dtype: int64

 CASE STATUS DISTRIBUTION
case_status_clean
Closed                 1472
Open                   1096
Under Investigation    1073
Pending                 713
Name: count, dtype: int64

 SEVERITY DISTRIBUTION
severity_clean
Medium      1349
Critical    1337
Low         1032
High         990
Name: count, dtype: int64

 WEAPON DISTRIBUTION
weapon_clean
Firearm           1539
Blunt Object       932
Hands/Personal     659
Knife              646
None/Unarmed       344
Name: count, dtype: int64

ONLINE REPORTING RATE
reported_online_clean
False    50.42
True     49.58
Name: proportion, dtype: float64

INCIDENTS BY YEAR
year
2018.0    598
2019.0    625
2020.0    602
2021.0    621
2022.0    653
2023.0    611
2024.0    647
Name: count, dtype: int64